# Generated by Django 2.1.7 on 2019-04-05 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='fh_item_id',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='This is the FareHarbor item for your activity', verbose_name='fareharbor item id'),
        ),
    ]
