# Generated by Django 2.1.7 on 2019-04-08 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_activity_fh_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='fh_item_id',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='This is the FareHarbor item for your activity. If your activity is free, please this blank', null=True, verbose_name='fareharbor item id'),
        ),
    ]
