# Generated by Django 2.1.7 on 2019-04-16 07:38

import activities.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_auto_20190415_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='address',
            field=models.CharField(help_text='Enter a meeting place for the activity', max_length=255, verbose_name='meeting place'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='featured_photo',
            field=models.ImageField(default='defaults/default_region.jpg', help_text='This photo will be featured on listings and the topof your activity page.', upload_to=activities.models.get_featured_image_filename, verbose_name='featured photo'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='fh_item_id',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='This is the FareHarbor item for your activity.', null=True, verbose_name='fareharbor item id'),
        ),
    ]
