# Generated by Django 2.1.7 on 2019-04-14 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_activity_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='image',
        ),
    ]
