# Generated by Django 2.1.7 on 2019-04-09 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_activityreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
