# Generated by Django 2.1.7 on 2019-04-24 06:56

import activities.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_auto_20190422_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='featured_photo',
            field=models.ImageField(default='defaults/default_activity.jpg', help_text='This photo will be featured on listings and the topof your activity page.', upload_to=activities.models.get_featured_image_filename, verbose_name='featured photo'),
        ),
    ]
