# Generated by Django 2.1.7 on 2019-04-29 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0007_auto_20190428_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Name of the category', max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='Name of the category in slug form (alphanumeric, hyphens, and underscores)', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(help_text='Name of the region', max_length=60),
        ),
        migrations.AlterField(
            model_name='region',
            name='slug',
            field=models.SlugField(help_text='Name of the region in slug form. (alphanumeric, hyphens, and underscores)', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(help_text='Name of the tag', max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(help_text='Name of the tag in slug form (alphanumeric, hyphen, and underscores)', max_length=20, unique=True),
        ),
    ]
