# Generated by Django 2.1.7 on 2019-04-29 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0008_auto_20190428_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='review_count',
        ),
    ]
