# Generated by Django 2.1.7 on 2019-05-01 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0009_remove_activity_review_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'permissions': (('moderate_activity', 'Can Moderate Activity'),), 'verbose_name': 'activity', 'verbose_name_plural': 'activities'},
        ),
    ]
