# Generated by Django 2.1.7 on 2019-05-01 22:19

from django.db import migrations
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0010_auto_20190430_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='approved_time',
        ),
        migrations.AlterField(
            model_name='activity',
            name='created',
            field=model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', when={'approved'}),
        ),
        migrations.AlterField(
            model_name='activity',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='unapproved', help_text='What is the current status of the activity?', max_length=100, no_check_for_status=True),
        ),
    ]
