# Generated by Django 2.1.7 on 2019-03-10 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Your name or organization. Will be displayed on your profile and activities.', max_length=60, verbose_name='name')),
                ('description', models.TextField(blank=True, help_text='Tell us about you or your organization.', max_length=400, verbose_name='description')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Contact phone number', max_length=128, verbose_name='phone')),
                ('website', models.URLField(blank=True, help_text="Your or organization's website", verbose_name='website')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
