# Generated by Django 2.1.7 on 2019-03-12 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='host',
            old_name='name',
            new_name='_name',
        ),
    ]
