# Generated by Django 2.1.7 on 2019-03-21 06:08

import activities.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityphoto',
            name='file',
            field=models.ImageField(upload_to=activities.models.get_image_filename, verbose_name='Photo'),
        ),
    ]
