# Generated by Django 2.1.7 on 2019-04-24 22:47

import activities.validators
from django.db import migrations, models
import reviews.models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=reviews.models.get_review_image_filename, validators=[activities.validators.validate_image_size], verbose_name='review photo'),
        ),
    ]
