# Generated by Django 2.1.7 on 2019-04-09 06:43

from django.db import migrations, models
import reviews.models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityreview',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=reviews.models.get_review_image_filename, verbose_name='review photo'),
        ),
    ]
