# Generated by Django 2.1.7 on 2019-04-14 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='show_name',
            field=models.BooleanField(default=False, help_text='Show your name in public. You can see still your name, regardless if checked or not.'),
        ),
    ]
