# Generated by Django 2.1.7 on 2019-04-26 04:24

import activities.validators
from django.db import migrations
import reviews.models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20190424_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='photo',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=reviews.models.get_review_image_filename, validators=[activities.validators.validate_image_size], verbose_name='review photo'),
        ),
    ]
