# Generated by Django 2.1.7 on 2019-05-03 06:14

import activities.validators
from django.db import migrations, models
import reviews.models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20190425_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(help_text='Write about the activity.', max_length=500, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='review',
            name='photo',
            field=sorl.thumbnail.fields.ImageField(blank=True, help_text='Upload a photo you have taken during the activity.', null=True, upload_to=reviews.models.get_review_image_filename, validators=[activities.validators.validate_image_size], verbose_name='review photo'),
        ),
    ]
