# Generated by Django 2.1.5 on 2019-02-26 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(max_length=400, verbose_name='description')),
                ('hightlights', models.TextField(max_length=400, verbose_name='highlights')),
                ('requirements', models.TextField(blank=True, max_length=400, verbose_name='requirements')),
                ('address', models.CharField(max_length=255, verbose_name='address')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='latitude')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='longitude')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='price')),
                ('review_count', models.IntegerField(blank=True, default=0, verbose_name='review count')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='activity created date')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'activity',
                'verbose_name_plural': 'activities',
            },
        ),
        migrations.CreateModel(
            name='ActivityImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=60)),
                ('image', models.ImageField(upload_to='activity_images/')),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='activity.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('image', models.ImageField(upload_to='region')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('font_awesome', models.CharField(max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.Region', verbose_name='region'),
        ),
        migrations.AddField(
            model_name='activity',
            name='tags',
            field=models.ManyToManyField(blank=True, to='activity.Tag', verbose_name='tags'),
        ),
    ]
