# Generated by Django 2.1.7 on 2019-02-26 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='hightlights',
            new_name='highlights',
        ),
    ]
