# Generated by Django 2.1.7 on 2019-04-19 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='fh_username',
            field=models.CharField(blank=True, default='travel2change', help_text='Enter your FareHarbor username. This is required if you are hosting paid activities', max_length=60, verbose_name='fareharbor username'),
        ),
    ]
