# Generated by Django 2.1.7 on 2019-04-26 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190419_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='points',
            field=models.IntegerField(default=0, editable=False, verbose_name='points'),
        ),
    ]
