# Generated by Django 2.1.7 on 2019-04-29 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190428_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Enter an email address that you like visitors to contact.', max_length=255, verbose_name='contact email'),
        ),
    ]
