# Generated by Django 2.1.7 on 2019-04-27 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointvalue',
            name='key',
            field=models.CharField(help_text='Choose a key name of this point value', max_length=50, unique=True, verbose_name='key'),
        ),
    ]
